# syntax=docker/dockerfile:1

FROM maven


RUN mkdir /usr/src/app

WORKDIR /usr/src/app

COPY Libraries /usr/src/app/Libraries
COPY Projects /usr/src/app/Projects
COPY src /usr/src/app/src



WORKDIR /usr/src/app/Libraries/UtilLib
