insert into cities (name) values ('Soroti');
insert into cities (name) values ('Tlumach');
insert into cities (name) values ('La Unión');
insert into cities (name) values ('Tempuran');
insert into cities (name) values ('Ivanovka');
insert into cities (name) values ('Santa Cruz');
insert into cities (name) values ('Hlusk');
insert into cities (name) values ('Calebasses');
insert into cities (name) values ('Velestíno');
insert into cities (name) values ('Santo André');
insert into cities (name) values ('West Island');
insert into cities (name) values ('Le Lamentin');
insert into cities (name) values ('Zadní Mostek');
insert into cities (name) values ('Chengmagang');
insert into cities (name) values ('Cotabambas');
insert into cities (name) values ('Sigeng');
insert into cities (name) values ('Växjö');
insert into cities (name) values ('Long Xuyên');
insert into cities (name) values ('Kosów Lacki');
insert into cities (name) values ('Niigata-shi');
insert into cities (name) values ('Popasna');
insert into cities (name) values ('Timiryazevo');
insert into cities (name) values ('San Sebastián');
insert into cities (name) values ('McKinley');
insert into cities (name) values ('Kolomanu');
insert into cities (name) values ('Towa');
insert into cities (name) values ('Oklahoma City');
insert into cities (name) values ('Xinhang');
insert into cities (name) values ('Colorado Springs');
insert into cities (name) values ('Tashi');
insert into cities (name) values ('Berëzovskiy');
insert into cities (name) values ('Breia');
insert into cities (name) values ('Eskilstuna');
insert into cities (name) values ('Temenggungan');
insert into cities (name) values ('Saint Cloud');
insert into cities (name) values ('Saray');
insert into cities (name) values ('Velestíno');
insert into cities (name) values ('Sutukung');
insert into cities (name) values ('Sigou');
insert into cities (name) values ('Orodo');
insert into cities (name) values ('Putukrejo');
insert into cities (name) values ('San Miguel del Padrón');
insert into cities (name) values ('Nal’chik');
insert into cities (name) values ('Żabno');
insert into cities (name) values ('Mancos');
insert into cities (name) values ('Shicang');
insert into cities (name) values ('Ribeira Quente');
insert into cities (name) values ('Silae');
insert into cities (name) values ('Norak');
insert into cities (name) values ('Kadubamban');
insert into cities (name) values ('Hujiaba');
insert into cities (name) values ('Brusartsi');
insert into cities (name) values ('Qili');
insert into cities (name) values ('Velestíno');
insert into cities (name) values ('Dongming Chengguanzhen');
insert into cities (name) values ('Budva');
insert into cities (name) values ('Loppi');
insert into cities (name) values ('Koblain');
insert into cities (name) values ('Birayang');
insert into cities (name) values ('Miaoxi');
insert into cities (name) values ('Kosan');
insert into cities (name) values ('Malinaw');
insert into cities (name) values ('Taltal');
insert into cities (name) values ('Rokytne');
insert into cities (name) values ('Hong’an');
insert into cities (name) values ('Kalimeneng');
insert into cities (name) values ('Oni');
insert into cities (name) values ('Trostyanets’');
insert into cities (name) values ('Luyi');
insert into cities (name) values ('Requião');
insert into cities (name) values ('Trmice');
insert into cities (name) values ('Melíssia');
insert into cities (name) values ('Ostuncalco');
insert into cities (name) values ('Zibo');
insert into cities (name) values ('Kansas City');
insert into cities (name) values ('Masumbwe');
insert into cities (name) values ('Gus’-Khrustal’nyy');
insert into cities (name) values ('Paseyan');
insert into cities (name) values ('Sikka');
insert into cities (name) values ('Gujō');
insert into cities (name) values ('Sundbyberg');
insert into cities (name) values ('Bugcaon');
insert into cities (name) values ('Zishan');
insert into cities (name) values ('Bulacan');
insert into cities (name) values ('Matamey');
insert into cities (name) values ('Sakai');
insert into cities (name) values ('Đắk Song');
insert into cities (name) values ('Kouloúra');
insert into cities (name) values ('Boroon');
insert into cities (name) values ('Rokiciny');
insert into cities (name) values ('Dongshi');
insert into cities (name) values ('Dob');
insert into cities (name) values ('Velestíno');
insert into cities (name) values ('San Sebastián');
insert into cities (name) values ('Las Lajas');
insert into cities (name) values ('Oklahoma City');
insert into cities (name) values ('Siteía');
insert into cities (name) values ('Alburitel');
insert into cities (name) values ('Greystones');
insert into cities (name) values ('Lianrao');
insert into cities (name) values ('Odesskoye');
insert into cities (name) values ('Purranque');
insert into cities (name) values ('Zinder');
insert into cities (name) values ('Sanli');
insert into cities (name) values ('Mahaddayweyne');
insert into cities (name) values ('Sbo’o');
insert into cities (name) values ('Hòa Bình');
insert into cities (name) values ('Chuoyuan');
insert into cities (name) values ('Santiaoshi');
insert into cities (name) values ('Vikhorevka');
insert into cities (name) values ('São Luís do Quitunde');
insert into cities (name) values ('Doudleby nad Orlicí');
insert into cities (name) values ('Linqu');
insert into cities (name) values ('Tielu');
insert into cities (name) values ('Yanaoca');
insert into cities (name) values ('Buan');
insert into cities (name) values ('Lower Hutt');
insert into cities (name) values ('Quanxi');
insert into cities (name) values ('Garzón');
insert into cities (name) values ('Pridonskoy');
insert into cities (name) values ('Serpukhov');
insert into cities (name) values ('Cúcuta');
insert into cities (name) values ('Mourelos');
insert into cities (name) values ('Piteå');
insert into cities (name) values ('Cabaritan East');
insert into cities (name) values ('Baoxu');
insert into cities (name) values ('Kola');
insert into cities (name) values ('Alma');
insert into cities (name) values ('Luoyuan');
insert into cities (name) values ('Donim');
insert into cities (name) values ('Gwangju');
insert into cities (name) values ('Zhantang');
insert into cities (name) values ('Ojos de Agua');
insert into cities (name) values ('Rattanaburi');
insert into cities (name) values ('Orléans');
insert into cities (name) values ('Shizukuishi');
insert into cities (name) values ('Krajan Tegalombo');
insert into cities (name) values ('Joypur Hāt');
insert into cities (name) values ('Konobeyevo');
insert into cities (name) values ('Dawan');
insert into cities (name) values ('Campor');
insert into cities (name) values ('Keboncau');
insert into cities (name) values ('Keratéa');
insert into cities (name) values ('Zhongluotan');
insert into cities (name) values ('Paraíba do Sul');
insert into cities (name) values ('Kali');
insert into cities (name) values ('Bagangan');
insert into cities (name) values ('Chenxiang');
insert into cities (name) values ('Bangeran');
insert into cities (name) values ('Francova Lhota');
insert into cities (name) values ('El Carril');
insert into cities (name) values ('Oslo');
insert into cities (name) values ('Flandes');
insert into cities (name) values ('Yanwang');
insert into cities (name) values ('Karnobat');
insert into cities (name) values ('Pakapasan Girang');
insert into cities (name) values ('Sidowayah Lor');
insert into cities (name) values ('Usukhchay');
insert into cities (name) values ('Býšť');
insert into cities (name) values ('Fūman');
insert into cities (name) values ('Tieli');
insert into cities (name) values ('Văn Điển');
insert into cities (name) values ('Fengchuan');
insert into cities (name) values ('Palmeira das Missões');
insert into cities (name) values ('Bamban');
insert into cities (name) values ('Gaozhuang');
insert into cities (name) values ('Kuala Lumpur');
insert into cities (name) values ('Kurashiki');
insert into cities (name) values ('Chinoz');
insert into cities (name) values ('Xiaruyue');
insert into cities (name) values ('Huaidian');
insert into cities (name) values ('Ciomas');
insert into cities (name) values ('Pīrgaaj');
insert into cities (name) values ('San Jose');
insert into cities (name) values ('Siekierczyn');
insert into cities (name) values ('Bendilwungu Lor');
insert into cities (name) values ('Agrela');
insert into cities (name) values ('Stutterheim');
insert into cities (name) values ('Ippy');
insert into cities (name) values ('Kajaani');
insert into cities (name) values ('Tanghu');
insert into cities (name) values ('Penaraga');
insert into cities (name) values ('Kemuning');
insert into cities (name) values ('Komsomol’skiy');
insert into cities (name) values ('Qacha’s Nek');
insert into cities (name) values ('Shirone');
insert into cities (name) values ('Pueblo Nuevo');
insert into cities (name) values ('Doug An');
insert into cities (name) values ('Samut Sakhon');
insert into cities (name) values ('Gudauta');
insert into cities (name) values ('Toulouse');
insert into cities (name) values ('Sucre');
insert into cities (name) values ('Okinawa');
insert into cities (name) values ('Lagodekhi');
insert into cities (name) values ('Sukasari');
insert into cities (name) values ('Taikang');
insert into cities (name) values ('Viale');
insert into cities (name) values ('Thị Trấn Cao Lộc');
insert into cities (name) values ('Sindangsari');
insert into cities (name) values ('Wewit');
insert into cities (name) values ('Aknīste');
insert into cities (name) values ('Jambesari');
insert into cities (name) values ('Donja Dubica');
insert into cities (name) values ('Dingle');
insert into cities (name) values ('Limoges');
insert into cities (name) values ('Jiaoxie');
insert into cities (name) values ('Liuzhi');
insert into cities (name) values ('Sinop');
insert into cities (name) values ('Paurito');
insert into cities (name) values ('Mitry-Mory');
insert into cities (name) values ('Atalaia');
insert into cities (name) values ('Bergamo');
insert into cities (name) values ('Ai Tu');
insert into cities (name) values ('Roma');
insert into cities (name) values ('Independence');
insert into cities (name) values ('Wenquan');
insert into cities (name) values ('Libertad');
insert into cities (name) values ('Quibal');
insert into cities (name) values ('Habana del Este');
insert into cities (name) values ('Belung Satu');
insert into cities (name) values ('Lusacan');
insert into cities (name) values ('Slatina');
insert into cities (name) values ('Kolambugan');
insert into cities (name) values ('Palana');
insert into cities (name) values ('San Francisco');
insert into cities (name) values ('Ciudad Nueva');
insert into cities (name) values ('Pegongan');
insert into cities (name) values ('Jemielno');
insert into cities (name) values ('Pizhma');
insert into cities (name) values ('Arevik');
insert into cities (name) values ('Épinal');
insert into cities (name) values ('Banyubang');
insert into cities (name) values ('Shuangpu');
insert into cities (name) values ('Obeliai');
insert into cities (name) values ('Buganda');
insert into cities (name) values ('Linköping');
insert into cities (name) values ('Kommunar');
insert into cities (name) values ('Fécamp');
insert into cities (name) values ('Ransiki');
insert into cities (name) values ('Caluquembe');
insert into cities (name) values ('Psary');
insert into cities (name) values ('Oesena');
insert into cities (name) values ('Nový Knín');
insert into cities (name) values ('Jieshou');
insert into cities (name) values ('Huxu');
insert into cities (name) values ('Nanxi');
insert into cities (name) values ('Greenland');
insert into cities (name) values ('Pogwizdów');
insert into cities (name) values ('Tríkeri');
insert into cities (name) values ('Montpellier');
insert into cities (name) values ('Grand Forks');
insert into cities (name) values ('Tawaramoto');
insert into cities (name) values ('Puerto Rico');
insert into cities (name) values ('Qingfeng');
insert into cities (name) values ('Buenavista');
insert into cities (name) values ('Campo Largo');
insert into cities (name) values ('Shuanggang');
insert into cities (name) values ('Panjiawan');
insert into cities (name) values ('Jobabo');
insert into cities (name) values ('Monching');
insert into cities (name) values ('Suocheng');
insert into cities (name) values ('Zielonki');
insert into cities (name) values ('Khust');
insert into cities (name) values ('Tyresö');
insert into cities (name) values ('Jocotán');
insert into cities (name) values ('San Eduardo');
insert into cities (name) values ('Baranowo');
insert into cities (name) values ('Hiseti');
insert into cities (name) values ('General Levalle');
insert into cities (name) values ('Semey');
insert into cities (name) values ('Murici');
insert into cities (name) values ('Berón de Astrada');
insert into cities (name) values ('Kemang');
insert into cities (name) values ('Granada');
insert into cities (name) values ('San Antonio de Los Altos');
insert into cities (name) values ('Ursus');
insert into cities (name) values ('Luleå');
insert into cities (name) values ('Cibingbin');
insert into cities (name) values ('Curpahuasi');
insert into cities (name) values ('Feuknoni');
insert into cities (name) values ('Paraiso');
insert into cities (name) values ('Lomma');
insert into cities (name) values ('Orocué');
insert into cities (name) values ('Chang’an');
insert into cities (name) values ('Tabunok');
insert into cities (name) values ('Kapenguria');
insert into cities (name) values ('Unión');
insert into cities (name) values ('Pasauran');
insert into cities (name) values ('Pag');
insert into cities (name) values ('Stan-Bekhtemir');
insert into cities (name) values ('Sahagún');
insert into cities (name) values ('Xiwu');
insert into cities (name) values ('Julita');
insert into cities (name) values ('Sangtian');
insert into cities (name) values ('Trnovlje pri Celju');
insert into cities (name) values ('Kashihara');
insert into cities (name) values ('Kamyzyak');
insert into cities (name) values ('Eslāmābād');
insert into cities (name) values ('Dortmund');
insert into cities (name) values ('Rumphi');
insert into cities (name) values ('Sampacho');
insert into cities (name) values ('Vegreville');
insert into cities (name) values ('Los Andes');
insert into cities (name) values ('Aguada de Pasajeros');
insert into cities (name) values ('Göteborg');
insert into cities (name) values ('Daping');
insert into cities (name) values ('Kotabaru Hilir');
insert into cities (name) values ('Lamas');
insert into cities (name) values ('Vilarinho das Cambas');
insert into cities (name) values ('Sobreda');
insert into cities (name) values ('Hengshan');
insert into cities (name) values ('Krasiczyn');
insert into cities (name) values ('Kotadukuh');
insert into cities (name) values ('Sandgerði');
insert into cities (name) values ('Al Jīzah');
insert into cities (name) values ('Tajinan');
insert into cities (name) values ('Naukšēni');
insert into cities (name) values ('Uppsala');
insert into cities (name) values ('Majiao');
insert into cities (name) values ('Doug An');
insert into cities (name) values ('Krynki');
insert into cities (name) values ('Janiuay');
insert into cities (name) values ('Malaga');
insert into cities (name) values ('Langtou');
insert into cities (name) values ('Pekijing');
insert into cities (name) values ('Mosina');
insert into cities (name) values ('Longquan');
insert into cities (name) values ('Gedongmulyo');
insert into cities (name) values ('Regidor');
insert into cities (name) values ('Hannō');
insert into cities (name) values ('Machov');
insert into cities (name) values ('São Mateus do Maranhão');
insert into cities (name) values ('Golynki');
insert into cities (name) values ('Kavarna');
insert into cities (name) values ('Pegões');
insert into cities (name) values ('Balindong');
insert into cities (name) values ('Jiuxian');
insert into cities (name) values ('As Suwaydā’');
insert into cities (name) values ('Kuala Lumpur');
insert into cities (name) values ('Luohe');
insert into cities (name) values ('Heping');
insert into cities (name) values ('Pukkila');
insert into cities (name) values ('Manosque');
insert into cities (name) values ('Yunchi');
insert into cities (name) values ('Sawara');
insert into cities (name) values ('Coro');
insert into cities (name) values ('Voskopojë');
insert into cities (name) values ('Pingfeng');
insert into cities (name) values ('Santa Bárbara');
insert into cities (name) values ('San Pedro Carchá');
insert into cities (name) values ('Melrose');
insert into cities (name) values ('Cajueiro');
insert into cities (name) values ('Wuquan');
insert into cities (name) values ('Muli');
insert into cities (name) values ('Changlu');
insert into cities (name) values ('Olejet');
insert into cities (name) values ('Huizhai');
insert into cities (name) values ('Sindangsari');
insert into cities (name) values ('Metulla');
insert into cities (name) values ('Jindong');
insert into cities (name) values ('Moerewa');
insert into cities (name) values ('Upper San Mateo');
insert into cities (name) values ('Sidamulya Satu');
insert into cities (name) values ('Bayeman');
insert into cities (name) values ('Lingqian');
insert into cities (name) values ('Borok');
insert into cities (name) values ('Lap Lae');
insert into cities (name) values ('Palmar de Varela');
insert into cities (name) values ('Quba');
insert into cities (name) values ('Khirdalan');
insert into cities (name) values ('Bayeman');
insert into cities (name) values ('Doljevac');
insert into cities (name) values ('Kawaguchi');
insert into cities (name) values ('Jiangjing');
insert into cities (name) values ('Burevestnik');
insert into cities (name) values ('Drawno');
insert into cities (name) values ('Boje');
insert into cities (name) values ('Phitsanulok');
insert into cities (name) values ('Ekou');
insert into cities (name) values ('Duzhenwan');
insert into cities (name) values ('Potosí');
insert into cities (name) values ('Manjo');
insert into cities (name) values ('Bato');
insert into cities (name) values ('Prainha de Baixo');
insert into cities (name) values ('Dongdu');
insert into cities (name) values ('Morelos');
insert into cities (name) values ('Tidili Mesfioua');
insert into cities (name) values ('Beiping');
insert into cities (name) values ('Hroznětín');
insert into cities (name) values ('Erbil');
insert into cities (name) values ('Zhufo');
insert into cities (name) values ('Cardona');
insert into cities (name) values ('Khŭjand');
insert into cities (name) values ('Mitsuke');
insert into cities (name) values ('Dahedian');
insert into cities (name) values ('Houston');
insert into cities (name) values ('Veldhoven');
insert into cities (name) values ('Jiangxi');
insert into cities (name) values ('Haishan');
insert into cities (name) values ('Pyzdry');
insert into cities (name) values ('Sobreira');
insert into cities (name) values ('Arlington');
insert into cities (name) values ('Nuits-Saint-Georges');
insert into cities (name) values ('Zhouzhuang');
insert into cities (name) values ('Mozi');
insert into cities (name) values ('Inuotose');
insert into cities (name) values ('Managua');
insert into cities (name) values ('Cestas');
insert into cities (name) values ('Kifrī');
insert into cities (name) values ('Nālūt');
insert into cities (name) values ('Tanjung Pandan');
insert into cities (name) values ('Henggouqiao');
insert into cities (name) values ('Cereté');
insert into cities (name) values ('Monastir');
insert into cities (name) values ('Walnut Grove');
insert into cities (name) values ('Al Qaţn');
insert into cities (name) values ('Lago dos Rodrigues');
insert into cities (name) values ('Infantas');
insert into cities (name) values ('Saint-Jouan-des-Guérets');
insert into cities (name) values ('Apengjiang');
insert into cities (name) values ('Antsohimbondrona');
insert into cities (name) values ('Lapa do Lobo');
insert into cities (name) values ('Santana do Paraíso');
insert into cities (name) values ('Jacareí');
insert into cities (name) values ('Mbigou');
insert into cities (name) values ('Nowa Góra');
insert into cities (name) values ('Curry');
insert into cities (name) values ('Lyubar');
insert into cities (name) values ('Sukorejo');
insert into cities (name) values ('Millerovo');
insert into cities (name) values ('Pogranichnyy');
insert into cities (name) values ('Saint-Quentin-en-Yvelines');
insert into cities (name) values ('Drosáto');
insert into cities (name) values ('Gaozhuang');
insert into cities (name) values ('Mabua');
insert into cities (name) values ('Dédougou');
insert into cities (name) values ('Talcahuano');
insert into cities (name) values ('Drajak');
insert into cities (name) values ('Wałcz');
insert into cities (name) values ('Xihu');
insert into cities (name) values ('Sancha');
insert into cities (name) values ('Wien');
insert into cities (name) values ('Niaohe');
insert into cities (name) values ('Quangang');
insert into cities (name) values ('Susunan');
insert into cities (name) values ('Shuangxiqiao');
insert into cities (name) values ('Nisporeni');
insert into cities (name) values ('Marco');
insert into cities (name) values ('Shijiazhai');
insert into cities (name) values ('Kovilj');
insert into cities (name) values ('Opatowiec');
insert into cities (name) values ('Meikeng');
insert into cities (name) values ('Lolotique');
insert into cities (name) values ('Rochester');
insert into cities (name) values ('Madrid');
insert into cities (name) values ('Pasadena');
insert into cities (name) values ('Quilpué');
insert into cities (name) values ('Caja');
insert into cities (name) values ('Zhifudao');
insert into cities (name) values ('Gjirokastër');
insert into cities (name) values ('Ternopil’');
insert into cities (name) values ('Prażmów');
insert into cities (name) values ('Novyy Svit');
insert into cities (name) values ('Marseille');
insert into cities (name) values ('Lyon');
insert into cities (name) values ('San Matías');
insert into cities (name) values ('Rejanegara');
insert into cities (name) values ('Tonekābon');
insert into cities (name) values ('Aleg');
insert into cities (name) values ('Looc');
insert into cities (name) values ('Hayil');
insert into cities (name) values ('Xuhang');
insert into cities (name) values ('Babug');
insert into cities (name) values ('Wanfang');
insert into cities (name) values ('Keruguya');
insert into cities (name) values ('Nyahururu');
insert into cities (name) values ('Lalagsan');
insert into cities (name) values ('Bunobogu');
insert into cities (name) values ('Berlin');
insert into cities (name) values ('Boro');
insert into cities (name) values ('Aomori Shi');
insert into cities (name) values ('Buenavista');
insert into cities (name) values ('Horad Rechytsa');
insert into cities (name) values ('Murmuiža');
insert into cities (name) values ('Santol');
insert into cities (name) values ('Alcainça');
insert into cities (name) values ('Kowary');
insert into cities (name) values ('Barberton');
insert into cities (name) values ('Batutua');
insert into cities (name) values ('Tuban');
insert into cities (name) values ('Jeminay');
insert into cities (name) values ('Mar del Plata');
insert into cities (name) values ('Changqing');
insert into cities (name) values ('Karlobag');
insert into cities (name) values ('Gubin');
insert into cities (name) values ('Banjar Medura');
insert into cities (name) values ('Mingshan');
insert into cities (name) values ('Krasnopillya');
insert into cities (name) values ('Yanacancha');
insert into cities (name) values ('Al Jīzah');
insert into cities (name) values ('Karata');
insert into cities (name) values ('As Sayyānī');
insert into cities (name) values ('Pančevo');
insert into cities (name) values ('Imishli');
insert into cities (name) values ('Solntsevo');
insert into cities (name) values ('Karangbaru');
insert into cities (name) values ('Huo’erqi');
insert into cities (name) values ('Pahārpur');
insert into cities (name) values ('Auriflama');
insert into cities (name) values ('Pingtan');
insert into cities (name) values ('Jianchang');
insert into cities (name) values ('Talun');
insert into cities (name) values ('Xiaowuzhan');
insert into cities (name) values ('Guancheng');
insert into cities (name) values ('Tengah');
insert into cities (name) values ('Saribudolok');
insert into cities (name) values ('Farmahīn');
insert into cities (name) values ('Amirdzhan');
insert into cities (name) values ('Yangkou');
insert into cities (name) values ('Los Aquijes');
insert into cities (name) values ('Negombo');
insert into cities (name) values ('Saginaw');
insert into cities (name) values ('Hulín');
insert into cities (name) values ('Urbano Noris');
insert into cities (name) values ('Shimotoda');
insert into cities (name) values ('Gafsa');
insert into cities (name) values ('Rochester');
insert into cities (name) values ('Blarney');
insert into cities (name) values ('Nice');
insert into cities (name) values ('Pogranichnyy');
insert into cities (name) values ('Trới');
insert into cities (name) values ('Tapada das Mercês');
insert into cities (name) values ('Urengoy');
insert into cities (name) values ('La Plaine-Saint-Denis');
insert into cities (name) values ('Vera Cruz');
insert into cities (name) values ('Cibungur');
insert into cities (name) values ('Lezhë');
insert into cities (name) values ('Jiguan');
insert into cities (name) values ('Golynki');
insert into cities (name) values ('Rybinsk');
insert into cities (name) values ('Maikun');
insert into cities (name) values ('Vigia');
insert into cities (name) values ('Rionegro');
insert into cities (name) values ('Ribeira Grande');
insert into cities (name) values ('Santa Cruz del Sur');
insert into cities (name) values ('Norrköping');
insert into cities (name) values ('Medina Estates');
insert into cities (name) values ('Kauit');
insert into cities (name) values ('Wulan Hada');
insert into cities (name) values ('Aurora');
insert into cities (name) values ('Motomiya');
insert into cities (name) values ('Mariestad');
insert into cities (name) values ('Tamorong');
insert into cities (name) values ('Ar Rujum');
insert into cities (name) values ('Sotnikovskoye');
insert into cities (name) values ('Novyye Kuz’minki');
insert into cities (name) values ('Bragança Paulista');
insert into cities (name) values ('Bi’r Ḩāt');
insert into cities (name) values ('Leon');
insert into cities (name) values ('Sanchahe');
insert into cities (name) values ('Villaviciosa');
insert into cities (name) values ('Puerto Padre');
insert into cities (name) values ('Oehaunu');
insert into cities (name) values ('Masantol');
insert into cities (name) values ('Sîr ed Danniyé');
insert into cities (name) values ('Yeniköy');
insert into cities (name) values ('Dongxiao');
insert into cities (name) values ('Ngedhubasa');
insert into cities (name) values ('Berlín');
insert into cities (name) values ('Višňova');
insert into cities (name) values ('Norakert');
insert into cities (name) values ('Sarāvān');
insert into cities (name) values ('Dolní Bečva');
insert into cities (name) values ('Chuncheon');
insert into cities (name) values ('Duobagou');
insert into cities (name) values ('Kota Kinabalu');
insert into cities (name) values ('Klášterec nad Ohří');
insert into cities (name) values ('Cigintung');
insert into cities (name) values ('Tashanta');
insert into cities (name) values ('Semenivka');
insert into cities (name) values ('Yayva');
insert into cities (name) values ('Amaraji');
insert into cities (name) values ('Calais');
insert into cities (name) values ('Knežica');
insert into cities (name) values ('Musalerr');
insert into cities (name) values ('Damatulan');
insert into cities (name) values ('Fengcun');
insert into cities (name) values ('Huangshui');
insert into cities (name) values ('Debeljača');
insert into cities (name) values ('Shanxi');
insert into cities (name) values ('Linköping');
insert into cities (name) values ('Norton');
insert into cities (name) values ('Kurumoch');
insert into cities (name) values ('Tūkrah');
insert into cities (name) values ('Safotulafai');
insert into cities (name) values ('Gīvī');
insert into cities (name) values ('Karanganyar');
insert into cities (name) values ('Tatrang');
insert into cities (name) values ('Pryazovs’ke');
insert into cities (name) values ('Guangli');
insert into cities (name) values ('Huadian');
insert into cities (name) values ('Venda');
insert into cities (name) values ('Águia Branca');
insert into cities (name) values ('Rzeczenica');
insert into cities (name) values ('Nyrkiv');
insert into cities (name) values ('Washington');
insert into cities (name) values ('Łącko');
insert into cities (name) values ('Srinjine');
insert into cities (name) values ('Descalvado');
insert into cities (name) values ('Kadusimbar');
insert into cities (name) values ('Brka');
insert into cities (name) values ('Colonia Mauricio José Troche');
insert into cities (name) values ('Lautaro');
insert into cities (name) values ('Valence');
insert into cities (name) values ('Mueang Nonthaburi');
insert into cities (name) values ('Monte Novo');
insert into cities (name) values ('Liqiao');
insert into cities (name) values ('Tromsø');
insert into cities (name) values ('Taypano');
insert into cities (name) values ('Vónitsa');
insert into cities (name) values ('Pogwizdów');
insert into cities (name) values ('Velký Týnec');
insert into cities (name) values ('Onokivtsi');
insert into cities (name) values ('Novaya Tavolzhanka');
insert into cities (name) values ('Chaoyang');
insert into cities (name) values ('Banjar Serangan');
insert into cities (name) values ('Mekkaw');
insert into cities (name) values ('Armenia');
insert into cities (name) values ('Pingkai');
insert into cities (name) values ('Petrópolis');
insert into cities (name) values ('Delray Beach');
insert into cities (name) values ('Shar’ya');
insert into cities (name) values ('Wat Sing');
insert into cities (name) values ('Caiyuan');
insert into cities (name) values ('La Virginia');
insert into cities (name) values ('Morcellemont Saint André');
insert into cities (name) values ('Douala');
insert into cities (name) values ('Águia Branca');
insert into cities (name) values ('Wolbrom');
insert into cities (name) values ('Thanh Ba');
insert into cities (name) values ('Pau');
insert into cities (name) values ('Agkathiá');
insert into cities (name) values ('Kryry');
insert into cities (name) values ('Amangarh');
insert into cities (name) values ('Sucre');
insert into cities (name) values ('Örebro');
insert into cities (name) values ('Quibdó');
insert into cities (name) values ('Karangcombong');
insert into cities (name) values ('Västra Frölunda');
insert into cities (name) values ('Yuantan');
insert into cities (name) values ('Ciyun');
insert into cities (name) values ('Jiazi');
insert into cities (name) values ('Kostakioí');
insert into cities (name) values ('Dimona');
insert into cities (name) values ('Renchaoxi');
insert into cities (name) values ('Madīnat Sittah Uktūbar');
insert into cities (name) values ('Daru');
insert into cities (name) values ('Los Angeles');
insert into cities (name) values ('Matagami');
insert into cities (name) values ('Tayang');
insert into cities (name) values ('Varser');
insert into cities (name) values ('Sanfang');
insert into cities (name) values ('Ala');
insert into cities (name) values ('Kenitra');
insert into cities (name) values ('Ventersburg');
insert into cities (name) values ('Mionica');
insert into cities (name) values ('Yatsuomachi-higashikumisaka');
insert into cities (name) values ('Cavan');
insert into cities (name) values ('San Felipe');
insert into cities (name) values ('Pallasovka');
insert into cities (name) values ('Almeria');
insert into cities (name) values ('Libice nad Cidlinou');
insert into cities (name) values ('Hohoe');
insert into cities (name) values ('São João dos Montes');
insert into cities (name) values ('Cool űrhajó');
insert into cities (name) values ('Petaling Jaya');
insert into cities (name) values ('Davao');
insert into cities (name) values ('Alingsås');
insert into cities (name) values ('Mtwango');
insert into cities (name) values ('Bartolomé Masó');
insert into cities (name) values ('Basqal');
insert into cities (name) values ('Fahraj');
insert into cities (name) values ('Barra de São Francisco');
insert into cities (name) values ('Cinunjang');
insert into cities (name) values ('Łaszczów');
insert into cities (name) values ('Kitango');
insert into cities (name) values ('Villavicencio');
insert into cities (name) values ('Raposos');
insert into cities (name) values ('Leppävirta');
insert into cities (name) values ('Kisanga');
insert into cities (name) values ('San Francisco');
insert into cities (name) values ('Yangzi');
insert into cities (name) values ('Mórrope');
insert into cities (name) values ('Chanthaburi');
insert into cities (name) values ('Świecie');
insert into cities (name) values ('Loureiro');
insert into cities (name) values ('Barretos');
insert into cities (name) values ('Nanggewer');
insert into cities (name) values ('Bom Conselho');
insert into cities (name) values ('Lima Pampa');
insert into cities (name) values ('Bergen');
insert into cities (name) values ('Eastern Suburbs Mc');
insert into cities (name) values ('Haoping');
insert into cities (name) values ('Gokwe');
insert into cities (name) values ('Beringinjaya');
insert into cities (name) values ('Ágios Geórgios');
insert into cities (name) values ('Senhor da Serra');
insert into cities (name) values ('Baltasar Brum');
insert into cities (name) values ('Kamennogorsk');
insert into cities (name) values ('Columbus');
insert into cities (name) values ('Luqa');
insert into cities (name) values ('Almere Haven');
insert into cities (name) values ('Hualfín');
insert into cities (name) values ('San Isidro');
insert into cities (name) values ('Bogovarovo');
insert into cities (name) values ('Lapaz');
insert into cities (name) values ('Hisai');
insert into cities (name) values ('Sychëvo');
insert into cities (name) values ('Hluhluwe');
insert into cities (name) values ('Skolkovo');
insert into cities (name) values ('Santa Luzia');
insert into cities (name) values ('Haibeitou');
insert into cities (name) values ('Trujillo');
insert into cities (name) values ('Paynjuwayn');
insert into cities (name) values ('Pengshi');
insert into cities (name) values ('Shar');
insert into cities (name) values ('Kamenný Přívoz');
insert into cities (name) values ('Stuttgart');
insert into cities (name) values ('Pittsburgh');
insert into cities (name) values ('Phoenix');
insert into cities (name) values ('Drahichyn');
insert into cities (name) values ('Orkney');
insert into cities (name) values ('Pulau Pinang');
insert into cities (name) values ('Kedungasem');
insert into cities (name) values ('Tshaneni');
insert into cities (name) values ('Beigang');
insert into cities (name) values ('Comillas Norte');
insert into cities (name) values ('Busilak');
insert into cities (name) values ('Petersfield');
insert into cities (name) values ('Bayḩān');
insert into cities (name) values ('Paulpietersburg');
insert into cities (name) values ('Managua');
insert into cities (name) values ('Valle San Francisco');
insert into cities (name) values ('Lindome');
insert into cities (name) values ('Kiboga');
insert into cities (name) values ('Pittsburgh');
insert into cities (name) values ('Mielec');
insert into cities (name) values ('Sindangraja');
insert into cities (name) values ('Jaguarão');
insert into cities (name) values ('Sanlicheng');
insert into cities (name) values ('Yueyahe');
insert into cities (name) values ('Choropampa');
insert into cities (name) values ('Borne Sulinowo');
insert into cities (name) values ('San Enrique');
insert into cities (name) values ('Shchukino');
insert into cities (name) values ('Panganiban');
insert into cities (name) values ('Uttar Char Fasson');
insert into cities (name) values ('Mount Pearl');
insert into cities (name) values ('Cunha');
insert into cities (name) values ('San Pedro Masahuat');
insert into cities (name) values ('Ngajum');
insert into cities (name) values ('Mtsensk');
insert into cities (name) values ('Miras');
insert into cities (name) values ('Gò Dầu');
insert into cities (name) values ('Klatovy');
insert into cities (name) values ('Novoshakhtinskiy');
insert into cities (name) values ('Monywa');
insert into cities (name) values ('Nangerang');
insert into cities (name) values ('Talok');
insert into cities (name) values ('Granada');
insert into cities (name) values ('Dongfeng');
insert into cities (name) values ('Charqueadas');
insert into cities (name) values ('Oklahoma City');
insert into cities (name) values ('Changjiang');
insert into cities (name) values ('Ratnapura');
insert into cities (name) values ('Baykit');
insert into cities (name) values ('Opol');
insert into cities (name) values ('Krajan Demit');
insert into cities (name) values ('Ambelókipoi');
insert into cities (name) values ('Gia Nghĩa');
insert into cities (name) values ('Phoenix');
insert into cities (name) values ('Matam');
insert into cities (name) values ('Caeté');
insert into cities (name) values ('Myronivka');
insert into cities (name) values ('Basicao Coastal');
insert into cities (name) values ('Abbeville');
insert into cities (name) values ('Tisma');
insert into cities (name) values ('Puan');
insert into cities (name) values ('Emporeío');
insert into cities (name) values ('Bukavu');
insert into cities (name) values ('Colmar');
insert into cities (name) values ('Kokologo');
insert into cities (name) values ('Schellenberg');
insert into cities (name) values ('Banja Luka');
insert into cities (name) values ('Dafeng');
insert into cities (name) values ('Bilaran');
insert into cities (name) values ('Majia');
insert into cities (name) values ('Makhalino');
insert into cities (name) values ('Koktokay');
insert into cities (name) values ('Tāklisah');
insert into cities (name) values ('San Roque');
insert into cities (name) values ('San Diego');
insert into cities (name) values ('Agboville');
insert into cities (name) values ('Shemonaīkha');
insert into cities (name) values ('Rumilly');
insert into cities (name) values ('Jacareí');
insert into cities (name) values ('Odessa');
insert into cities (name) values ('Falun');
insert into cities (name) values ('Timaru');
insert into cities (name) values ('Tambo');
insert into cities (name) values ('Duyên Hải');
insert into cities (name) values ('Carianos');
insert into cities (name) values ('Mmaaf');
insert into cities (name) values ('Pyshchug');
insert into cities (name) values ('Busilak');
insert into cities (name) values ('Wangon');
insert into cities (name) values ('Perpignan');
insert into cities (name) values ('Sapeken');
insert into cities (name) values ('Heshui');
insert into cities (name) values ('Yixi');
insert into cities (name) values ('Dobryatino');
insert into cities (name) values ('Hujia');
insert into cities (name) values ('Jatirogo');
insert into cities (name) values ('Świdnica');
insert into cities (name) values ('Zvëzdnyy');
insert into cities (name) values ('Ljungby');
insert into cities (name) values ('Castanheira');
insert into cities (name) values ('San Casimiro');
insert into cities (name) values ('Le Havre');
insert into cities (name) values ('Guangshan Chengguanzhen');
insert into cities (name) values ('Catbalogan');
insert into cities (name) values ('Jahrom');
insert into cities (name) values ('Siraway');
insert into cities (name) values ('Fontenay-sous-Bois');
insert into cities (name) values ('Świecie nad Osą');
insert into cities (name) values ('Varnávas');
insert into cities (name) values ('Rayong');
insert into cities (name) values ('Millet');
insert into cities (name) values ('Glasgow');
insert into cities (name) values ('Zheng’an');
insert into cities (name) values ('Puerto Deseado');
insert into cities (name) values ('Aliuroba');
insert into cities (name) values ('Créteil');
insert into cities (name) values ('Helsingborg');
insert into cities (name) values ('Beauvais');
insert into cities (name) values ('Shanguang');
insert into cities (name) values ('Berea');
insert into cities (name) values ('Mbanga');
insert into cities (name) values ('Bogorejo');
insert into cities (name) values ('Malimaneek');
insert into cities (name) values ('Příšovice');
insert into cities (name) values ('Kortowo');
insert into cities (name) values ('Vilémov');
insert into cities (name) values ('Belford Roxo');
insert into cities (name) values ('Serrinha');
insert into cities (name) values ('Połaniec');
insert into cities (name) values ('Ambatolampy');
insert into cities (name) values ('Al Matūn');
insert into cities (name) values ('Karolino-Buhaz');
insert into cities (name) values ('Castanheira');
insert into cities (name) values ('As Sukhnah');
insert into cities (name) values ('Debre Tabor');
insert into cities (name) values ('Mata de São João');
insert into cities (name) values ('Pilaya');
insert into cities (name) values ('Bluefields');
insert into cities (name) values ('Baruta');
insert into cities (name) values ('Xinchengzi');
insert into cities (name) values ('Okhtyrka');
insert into cities (name) values ('Zavitinsk');
insert into cities (name) values ('Al Miqdādīyah');
insert into cities (name) values ('Campelos');
insert into cities (name) values ('Yeghvard');
insert into cities (name) values ('Tamboril');
insert into cities (name) values ('Krayen');
insert into cities (name) values ('Ratchaburi');
insert into cities (name) values ('Soio');
insert into cities (name) values ('Venda Nova');
insert into cities (name) values ('Povarovo');
insert into cities (name) values ('Kokkinóchoma');
insert into cities (name) values ('Pršovce');
insert into cities (name) values ('Mirny');
insert into cities (name) values ('Jianrao');
insert into cities (name) values ('Łęknica');
insert into cities (name) values ('Viangxai');
insert into cities (name) values ('Agdzhabedy');
insert into cities (name) values ('Bendan');
insert into cities (name) values ('Malayal');
insert into cities (name) values ('Digby');
insert into cities (name) values ('Shijing');
insert into cities (name) values ('San José de Bocay');
insert into cities (name) values ('Ouango');
insert into cities (name) values ('Hechun');
insert into cities (name) values ('Huanxi');
insert into cities (name) values ('Sofia');
insert into cities (name) values ('Saboyá');
insert into cities (name) values ('Vagonoremont');
insert into cities (name) values ('Golina');
insert into cities (name) values ('Poykovskiy');
insert into cities (name) values ('Cayna');
insert into cities (name) values ('Novovorontsovka');
insert into cities (name) values ('Međa');
insert into cities (name) values ('Zhizhong');
insert into cities (name) values ('Åtvidaberg');
insert into cities (name) values ('Berëza');
insert into cities (name) values ('Da’ao');
insert into cities (name) values ('Orleans');
insert into cities (name) values ('Bagalangit');
insert into cities (name) values ('Lindong');
insert into cities (name) values ('Mandal');
insert into cities (name) values ('Serra D''El Rei');
insert into cities (name) values ('Maguyam');
insert into cities (name) values ('Zomba');
insert into cities (name) values ('Minante Segundo');
insert into cities (name) values ('Jinjiang');
insert into cities (name) values ('Purwosari');
insert into cities (name) values ('Jiangcun');
insert into cities (name) values ('Vol’no-Nadezhdinskoye');
insert into cities (name) values ('Virginia');
insert into cities (name) values ('Tianxin');
insert into cities (name) values ('Nsok');
insert into cities (name) values ('Sơn Hà');
insert into cities (name) values ('Chengjiang');
insert into cities (name) values ('Lokosovo');
insert into cities (name) values ('Lebak Timur');
insert into cities (name) values ('Marataizes');
insert into cities (name) values ('Rashaant');
insert into cities (name) values ('Hebei');
insert into cities (name) values ('Sydney');
insert into cities (name) values ('Al Ḩashwah');
insert into cities (name) values ('Češinovo');
insert into cities (name) values ('Tarnowskie Góry');
insert into cities (name) values ('Pankrushikha');
insert into cities (name) values ('Chichigalpa');
insert into cities (name) values ('Kabaty');
insert into cities (name) values ('Surazh');
insert into cities (name) values ('Bắc Kạn');
insert into cities (name) values ('Bāgh-e Malek');
insert into cities (name) values ('Pio Duran');
insert into cities (name) values ('Matriz de Camaragibe');
insert into cities (name) values ('Rāipur');
insert into cities (name) values ('Enschede');
insert into cities (name) values ('Staré Město');
insert into cities (name) values ('Nakajah');
insert into cities (name) values ('Maoping');
insert into cities (name) values ('Mariestad');
insert into cities (name) values ('Morez');
insert into cities (name) values ('Līvāni');
insert into cities (name) values ('Plandirejo');
insert into cities (name) values ('Kourou');
insert into cities (name) values ('Cimongkor');
insert into cities (name) values ('Vitry-sur-Seine');
insert into cities (name) values ('Beauvais');
insert into cities (name) values ('Bongouanou');
insert into cities (name) values ('Coronel Vivida');
insert into cities (name) values ('Bibai');
insert into cities (name) values ('Chengxi');
insert into cities (name) values ('Blois');
insert into cities (name) values ('Sumbergayam');
insert into cities (name) values ('Privolzhsk');
insert into cities (name) values ('Yandang');
insert into cities (name) values ('Nishinomiya-hama');
insert into cities (name) values ('La Guadalupe');
insert into cities (name) values ('Svitlovods’k');
insert into cities (name) values ('Lugovskoy');
insert into cities (name) values ('Shengshan');
insert into cities (name) values ('Mališevo');
insert into cities (name) values ('Mercier');
insert into cities (name) values ('Villanueva');
insert into cities (name) values ('Martil');
insert into cities (name) values ('Malbork');
insert into cities (name) values ('Liozon');
insert into cities (name) values ('Tiébo');
insert into cities (name) values ('Mandepa Barat');
insert into cities (name) values ('Bodeh');
insert into cities (name) values ('Gemo');
insert into cities (name) values ('Stockholm');
insert into cities (name) values ('Dok Kham Tai');
insert into cities (name) values ('Tondano');
insert into cities (name) values ('Songzhuang');
insert into cities (name) values ('Kanugrahan');
insert into cities (name) values ('Calinaoan Malasin');
insert into cities (name) values ('Lubuagan');
insert into cities (name) values ('Tayasan');
insert into cities (name) values ('Fengyuan');
insert into cities (name) values ('Spånga');
insert into cities (name) values ('Täby');
insert into cities (name) values ('Pingqiao');
insert into cities (name) values ('Kalabahi');
insert into cities (name) values ('Brzozów');
insert into cities (name) values ('San Sebastián');
insert into cities (name) values ('Ålesund');
insert into cities (name) values ('Gayny');
insert into cities (name) values ('Likhoy');
insert into cities (name) values ('Shaxi');
insert into cities (name) values ('Myitkyina');
insert into cities (name) values ('Gaoqiaolou');
insert into cities (name) values ('Muesanaik');
insert into cities (name) values ('Petrovskaya');
insert into cities (name) values ('Silvares');
insert into cities (name) values ('Yaring');
