name: Pull Request Tests
on:
  pull_request:
    branches:
      - development
      - main
      - integration
      - unit-test

jobs:
  tests:
    runs-on: ubunut-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests
        run: |
          make unit-tests-docker